# sonar-project.properties
sonar.projectKey=mattdeakin_8.2CDevSecOps
sonar.organization=mattdeakin
sonar.host.url=https://sonarcloud.io
sonar.login=${708ddf95c9a47e017c31e75570d5ce3ceabf196a}
sonar.sources=.
sonar.exclusions=node_modules/**,test/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.projectName=NodeJS Goof Vulnerable App
sonar.sourceEncoding=UTF-8